## Обработка таблицы "Orders"

In [2]:
pip install arrow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 66 kB 2.9 MB/s 


In [3]:
import pandas as pd
import arrow 
from tqdm import tqdm
import pickle

In [71]:
data = pd.read_csv('orders.csv')

In [72]:
d0 = data.copy()

Достанем из столбца даты час и день недели

In [73]:
d0['date']=pd.to_datetime(d0['date'])
d0['hour'] = d0.date.dt.hour
d0['weekday'] = d0.date.dt.weekday.astype(int)

In [74]:
d0.head()

delivery_area_id                date  orders_cnt  hour  weekday
0                 0 2021-04-01 10:00:00           9    10        3
1                 0 2021-04-01 11:00:00           1    11        3
2                 0 2021-04-01 13:00:00           1    13        3
3                 0 2021-04-01 14:00:00           1    14        3
4                 0 2021-04-01 15:00:00           2    15        3

In [76]:
import numpy as np
d0['orders_cnt_normalized'] = np.zeros(884856)
d0.head()

delivery_area_id                date  orders_cnt  hour  weekday  \
0                 0 2021-04-01 10:00:00           9    10        3   
1                 0 2021-04-01 11:00:00           1    11        3   
2                 0 2021-04-01 13:00:00           1    13        3   
3                 0 2021-04-01 14:00:00           1    14        3   
4                 0 2021-04-01 15:00:00           2    15        3   

   orders_cnt_normalized  
0                    0.0  
1                    0.0  
2                    0.0  
3                    0.0  
4                    0.0

In [77]:
len(d0)

884856

In [79]:
normalized_df = pd.DataFrame(columns = ['delivery_area_id', 'date', 'orders_cnt', 'hour', 'weekday', 'orders_cnt_normalized', 'orders_cnt_finally_normalized'])
normalized_df

Empty DataFrame
Columns: [delivery_area_id, date, orders_cnt, hour, weekday, orders_cnt_normalized, orders_cnt_finally_normalized]
Index: []

In [83]:
areas = d0['delivery_area_id'].unique()

In [80]:
import statistics
import statistics
for area in areas:
  filtered_df = d0[d0['delivery_area_id'] == area]
  medians = []
  for i in range(7, len(filtered_df), 7):
      print(filtered_df['orders_cnt'][i-7:i].to_numpy())
      median_new = statistics.median(np.array(filtered_df['orders_cnt'][i-7:i]))
      filtered_df['orders_cnt_normalized'][i-7:i] = median_new
  filtered_df['orders_cnt_finally_normalized'] = filtered_df['orders_cnt'] / filtered_df['orders_cnt_normalized']
  df_append = normalized_df.append(filtered_df, ignore_index=True)
  normalized_df = df_append

[9 1 1 1 2 2 3]
[2 2 1 3 1 1 4]
[3 1 1 2 3 2 3]
[1 8 3 2 1 2 5]
[2 5 1 1 4 1 2]
[3 1 3 2 1 4 2]
[6 4 1 3 1 2 1]
[3 2 3 4 1 1 1]
[2 5 1 3 3 6 2]
[3 1 4 1 3 4 1]
[4 3 4 6 2 3 3]
[2 2 1 4 4 2 2]
[3 4 3 2 2 1 1]
[3 2 2 5 2 3 2]
[4 1 3 1 3 1 1]
[1 1 1 2 1 1 1]
[1 4 2 2 1 2 5]
[2 1 2 2 1 2 3]
[7 3 2 1 1 1 3]
[1 2 4 4 3 1 3]
[2 4 3 1 1 6 1]
[12  5  4  3  2  7  3]
[6 5 4 1 4 5 6]
[ 4  4  2  9 14  8  3]
[5 5 5 3 9 3 5]
[12 11  4  7  8  8  5]
[5 5 8 2 1 9 4]
[2 2 2 3 3 2 2]
[3 2 2 8 2 4 5]
[3 5 9 3 5 3 1]
[13  5  5  4  2  7  9]
[1 4 8 5 1 5 3]
[4 6 6 3 1 4 6]
[ 4 14  1  2  3  5  4]
[ 1  5  9  5  1 10  6]
[10  3 11  5  5  8  7]
[3 1 6 5 5 5 3]
[ 4  4  5  6 10  3  1]
[3 3 1 2 2 6 2]
[2 1 5 3 3 1 4]
[1 2 3 5 3 3 3]
[12  1  7  1  7  9  1]
[2 1 3 7 6 3 3]
[5 2 5 1 6 5 5]
[3 5 5 5 1 9 4]
[6 3 7 1 5 4 7]
[6 2 1 2 1 1 5]
[2 8 2 2 2 3 1]
[4 4 2 3 1 2 1]
[1 4 5 1 3 6 2]
[5 2 2 5 3 1 3]
[2 3 3 2 1 1 7]
[2 3 2 2 3 5 1]
[1 2 3 4 2 1 1]
[2 1 2 2 3 4 5]
[5 2 1 6 2 2 4]
[4 8 4 6 2 5 6]
[5 5 2 5 9 1 5]
[2 2 4 4 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:1105: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._set_values(indexer, value)


[5 7 1 5 5 4 3]
[2 2 3 1 6 5 5]
[1 2 9 2 4 3 6]
[2 2 9 5 1 8 2]
[ 9  7  7 10  4 10  3]
[8 4 6 5 4 5 6]
[ 4  3  5 11  8  3  7]
[5 3 3 1 1 4 3]
[4 1 9 5 6 3 2]
[9 1 4 7 5 3 3]
[1 5 3 6 5 1 3]
[3 5 3 6 6 4 2]
[5 4 3 4 2 3 3]
[4 6 6 5 4 5 2]
[1 5 6 2 4 1 7]
[8 3 1 4 5 5 5]
[5 9 6 3 7 2 8]
[1 2 6 6 6 6 6]
[ 6  2 12  9  6  3  3]
[7 6 6 4 2 3 2]
[6 3 9 2 1 4 1]
[5 4 6 3 9 3 4]
[6 5 1 1 2 3 5]
[ 4  1 10  4  3  3  3]
[9 5 3 9 4 3 8]
[4 3 2 7 5 4 3]
[7 3 3 2 5 5 5]
[4 6 4 5 4 4 6]
[ 1  1  8  2 12  3  6]
[6 7 7 5 8 5 3]
[10  4  3  4 10  3  2]
[1 2 5 4 1 5 4]
[5 2 8 7 6 3 8]
[5 5 7 3 4 4 8]
[4 3 6 5 1 2 2]
[5 3 7 1 7 3 5]
[ 5  4  6  4  1 14  5]
[7 5 5 7 4 2 2]
[3 6 4 5 6 4 5]
[ 4  3  6  6 12  5  3]
[6 3 4 6 5 5 4]
[ 2  5  2 10  4  7  6]
[3 5 1 8 5 6 6]
[ 4  4  2 11  7  3  5]
[5 3 2 4 3 2 4]
[1 6 5 4 4 2 5]
[ 5 12  6  8  8  2  7]
[6 4 8 4 4 7 4]
[ 3  6  4 16  6  6 12]
[4 2 4 9 8 3 6]
[ 1 11  1  3  3  2  5]
[ 4  5  3  4  4  1 10]
[9 4 5 3 4 6 5]
[ 5  3  9 11  9  6  9]
[4 4 7 4 4 5 4]
[ 2 13  8  7  6

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.


Выходные данные были обрезаны до нескольких последних строк (5000).
[1 3 1 2 1 4 2]
[5 1 2 1 3 3 1]
[1 1 2 1 1 2 1]
[2 2 1 2 2 1 1]
[4 1 1 6 3 1 3]
[3 1 2 1 2 7 2]
[2 2 4 2 3 2 4]
[2 1 2 1 4 1 2]
[5 3 3 1 4 3 6]
[1 3 3 1 1 3 2]
[3 1 2 1 3 1 1]
[2 2 2 1 5 3 2]
[2 6 3 6 8 2 6]
[6 4 3 7 4 3 3]
[4 5 4 5 2 3 2]
[2 1 1 2 2 3 1]
[9 2 3 1 3 5 4]
[2 1 2 5 2 1 2]
[8 3 2 2 2 1 1]
[4 2 1 2 1 3 1]
[2 1 2 3 1 3 1]
[2 1 4 1 1 5 1]
[4 1 2 2 4 1 2]
[4 1 4 3 5 1 1]
[2 1 1 2 4 6 3]
[1 1 3 2 1 1 1]
[1 2 1 2 1 1 2]
[1 2 1 4 2 3 1]
[1 2 1 2 1 1 1]
[4 2 1 1 1 2 3]
[2 2 3 2 4 1 1]
[2 5 1 6 1 3 2]
[7 2 1 1 1 3 1]
[6 5 7 2 3 2 4]
[2 1 1 1 7 4 6]
[3 3 3 2 3 3 1]
[4 7 4 5 5 3 4]
[4 3 2 1 1 1 1]
[4 3 5 4 4 4 5]
[3 3 1 1 7 5 4]
[5 1 4 2 3 3 1]
[1 5 1 1 5 3 1]
[2 2 1 2 3 3 6]
[2 1 1 6 1 7 4]
[4 2 4 5 4 1 1]
[4 1 8 4 5 1 4]
[1 2 2 1 5 8 4]
[5 6 2 5 1 2 2]
[4 5 8 2 7 5 2]
[2 2 2 1 5 3 4]
[1 3 1 4 4 4 5]
[1 1 4 3 1 4 2]
[2 4 6 6 2 9 4]
[ 1  5  3  3  2 12  6]
[5 7 3 2 2 6 2]
[2 5 1 6 6 3 2]
[2 1 1 6 1 3 4]
[5 3 3 1 2 1 

In [86]:
normalized_df

delivery_area_id                date orders_cnt hour weekday  \
0                     0 2021-04-01 10:00:00          9   10       3   
1                     0 2021-04-01 11:00:00          1   11       3   
2                     0 2021-04-01 13:00:00          1   13       3   
3                     0 2021-04-01 14:00:00          1   14       3   
4                     0 2021-04-01 15:00:00          2   15       3   
...                 ...                 ...        ...  ...     ...   
884851              592 2021-11-30 16:00:00          6   16       1   
884852              592 2021-11-30 17:00:00          3   17       1   
884853              592 2021-11-30 18:00:00          2   18       1   
884854              592 2021-11-30 19:00:00          4   19       1   
884855              592 2021-11-30 20:00:00          4   20       1   

        orders_cnt_normalized  orders_cnt_finally_normalized  
0                         2.0                           4.50  
1                         2.0                           0.50  
2                         2.0                           0.50  
3                         2.0                           0.50  
4                         2.0                           1.00  
...                       ...                            ...  
884851                    4.0                           1.50  
884852                    4.0                           0.75  
884853                    0.0                            inf  
884854                    0.0                            inf  
884855                    0.0                            inf  

[884856 rows x 7 columns]

In [89]:
for i in range(len(normalized_df)):
  if normalized_df['orders_cnt_finally_normalized'][i] == np.inf:
    normalized_df['orders_cnt_finally_normalized'][i] = 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [90]:
normalized_df

delivery_area_id                date orders_cnt hour weekday  \
0                     0 2021-04-01 10:00:00          9   10       3   
1                     0 2021-04-01 11:00:00          1   11       3   
2                     0 2021-04-01 13:00:00          1   13       3   
3                     0 2021-04-01 14:00:00          1   14       3   
4                     0 2021-04-01 15:00:00          2   15       3   
...                 ...                 ...        ...  ...     ...   
884851              592 2021-11-30 16:00:00          6   16       1   
884852              592 2021-11-30 17:00:00          3   17       1   
884853              592 2021-11-30 18:00:00          2   18       1   
884854              592 2021-11-30 19:00:00          4   19       1   
884855              592 2021-11-30 20:00:00          4   20       1   

        orders_cnt_normalized  orders_cnt_finally_normalized  
0                         2.0                           4.50  
1                         2.0                           0.50  
2                         2.0                           0.50  
3                         2.0                           0.50  
4                         2.0                           1.00  
...                       ...                            ...  
884851                    4.0                           1.50  
884852                    4.0                           0.75  
884853                    0.0                           0.00  
884854                    0.0                           0.00  
884855                    0.0                           0.00  

[884856 rows x 7 columns]

In [91]:
d0.to_csv('normalized_df')