## Обработка таблицы "Orders"

In [2]:
pip install arrow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 66 kB 2.9 MB/s 


In [3]:
import pandas as pd
import arrow 
from tqdm import tqdm
import pickle

In [4]:
data = pd.read_csv('orders.csv')

In [5]:
d0 = data.copy()

Достанем из столбца даты час и день недели

In [14]:
d0['date']=pd.to_datetime(d0['date'])
d0['hour'] = d0.date.dt.hour
d0['weekday'] = d0.date.dt.weekday.astype(int)

In [15]:
d0.head()

delivery_area_id                date  orders_cnt  hour  weekday
0                 0 2021-04-01 10:00:00           9    10        3
1                 0 2021-04-01 11:00:00           1    11        3
2                 0 2021-04-01 13:00:00           1    13        3
3                 0 2021-04-01 14:00:00           1    14        3
4                 0 2021-04-01 15:00:00           2    15        3

In [17]:
d0.shape

(884856, 5)

In [21]:
import numpy as np
d0['orders_cnt_normalized'] = np.zeros(884856)
d0.head()

delivery_area_id                date  orders_cnt  hour  weekday  \
0                 0 2021-04-01 10:00:00           9    10        3   
1                 0 2021-04-01 11:00:00           1    11        3   
2                 0 2021-04-01 13:00:00           1    13        3   
3                 0 2021-04-01 14:00:00           1    14        3   
4                 0 2021-04-01 15:00:00           2    15        3   

   orders_cnt_normalized  
0                    0.0  
1                    0.0  
2                    0.0  
3                    0.0  
4                    0.0

In [40]:
len(d0)

884856

In [50]:
import statistics
medians = []
for i in range(7, len(d0), 7):
    print(d0['orders_cnt'][i-7:i].to_numpy())
    median_new = statistics.median(np.array(d0['orders_cnt'][i-7:i]))
    d0['orders_cnt_normalized'][i-7:i] = median_new

[9 1 1 1 2 2 3]
[2 2 1 3 1 1 4]
[3 1 1 2 3 2 3]
[1 8 3 2 1 2 5]
[2 5 1 1 4 1 2]
[3 1 3 2 1 4 2]
[6 4 1 3 1 2 1]
[3 2 3 4 1 1 1]
[2 5 1 3 3 6 2]
[3 1 4 1 3 4 1]
[4 3 4 6 2 3 3]
[2 2 1 4 4 2 2]
[3 4 3 2 2 1 1]
[3 2 2 5 2 3 2]
[4 1 3 1 3 1 1]
[1 1 1 2 1 1 1]
[1 4 2 2 1 2 5]
[2 1 2 2 1 2 3]
[7 3 2 1 1 1 3]
[1 2 4 4 3 1 3]
[2 4 3 1 1 6 1]
[12  5  4  3  2  7  3]
[6 5 4 1 4 5 6]
[ 4  4  2  9 14  8  3]
[5 5 5 3 9 3 5]
[12 11  4  7  8  8  5]
[5 5 8 2 1 9 4]
[2 2 2 3 3 2 2]
[3 2 2 8 2 4 5]
[3 5 9 3 5 3 1]
[13  5  5  4  2  7  9]
[1 4 8 5 1 5 3]
[4 6 6 3 1 4 6]
[ 4 14  1  2  3  5  4]
[ 1  5  9  5  1 10  6]
[10  3 11  5  5  8  7]
[3 1 6 5 5 5 3]
[ 4  4  5  6 10  3  1]
[3 3 1 2 2 6 2]
[2 1 5 3 3 1 4]
[1 2 3 5 3 3 3]
[12  1  7  1  7  9  1]
[2 1 3 7 6 3 3]
[5 2 5 1 6 5 5]
[3 5 5 5 1 9 4]
[6 3 7 1 5 4 7]
[6 2 1 2 1 1 5]
[2 8 2 2 2 3 1]
[4 4 2 3 1 2 1]
[1 4 5 1 3 6 2]
[5 2 2 5 3 1 3]
[2 3 3 2 1 1 7]
[2 3 2 2 3 5 1]
[1 2 3 4 2 1 1]
[2 1 2 2 3 4 5]
[5 2 1 6 2 2 4]
[4 8 4 6 2 5 6]
[5 5 2 5 9 1 5]
[2 2 4 4 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Выходные данные были обрезаны до нескольких последних строк (5000).
[5 4 5 2 3 2 2]
[1 1 2 2 3 1 9]
[2 3 1 3 5 4 2]
[1 2 5 2 1 2 8]
[3 2 2 2 1 1 4]
[2 1 2 1 3 1 2]
[1 2 3 1 3 1 2]
[1 4 1 1 5 1 4]
[1 2 2 4 1 2 4]
[1 4 3 5 1 1 2]
[1 1 2 4 6 3 1]
[1 3 2 1 1 1 1]
[2 1 2 1 1 2 1]
[2 1 4 2 3 1 1]
[2 1 2 1 1 1 4]
[2 1 1 1 2 3 2]
[2 3 2 4 1 1 2]
[5 1 6 1 3 2 7]
[2 1 1 1 3 1 6]
[5 7 2 3 2 4 2]
[1 1 1 7 4 6 3]
[3 3 2 3 3 1 4]
[7 4 5 5 3 4 4]
[3 2 1 1 1 1 4]
[3 5 4 4 4 5 3]
[3 1 1 7 5 4 5]
[1 4 2 3 3 1 1]
[5 1 1 5 3 1 2]
[2 1 2 3 3 6 2]
[1 1 6 1 7 4 4]
[2 4 5 4 1 1 4]
[1 8 4 5 1 4 1]
[2 2 1 5 8 4 5]
[6 2 5 1 2 2 4]
[5 8 2 7 5 2 2]
[2 2 1 5 3 4 1]
[3 1 4 4 4 5 1]
[1 4 3 1 4 2 2]
[4 6 6 2 9 4 1]
[ 5  3  3  2 12  6  5]
[7 3 2 2 6 2 2]
[5 1 6 6 3 2 2]
[1 1 6 1 3 4 5]
[3 3 1 2 1 3 7]
[4 2 3 5 2 1 2]
[1 1 1 5 2 4 2]
[1 2 4 2 3 1 7]
[2 1 4 2 5 2 4]
[1 2 1 3 2 7 4]
[4 2 2 2 2 2 2]
[1 4 5 6 3 4 3]
[2 3 1 1 1 1 1]
[1 1 1 1 1 1 1]
[1 1 1 2 1 1 1]
[1 2 2 1 1 1 1]
[1 1 1 1 1 1 1]
[1 1 1 1 1 1 1]
[1 1 1 1 1 1 

In [51]:
d0.head()

delivery_area_id                date  orders_cnt  hour  weekday  \
0                 0 2021-04-01 10:00:00           9    10        3   
1                 0 2021-04-01 11:00:00           1    11        3   
2                 0 2021-04-01 13:00:00           1    13        3   
3                 0 2021-04-01 14:00:00           1    14        3   
4                 0 2021-04-01 15:00:00           2    15        3   

   orders_cnt_normalized  
0                    2.0  
1                    2.0  
2                    2.0  
3                    2.0  
4                    2.0

In [53]:
d0['orders_cnt_finally_normalized'] = d0['orders_cnt'] / d0['orders_cnt_normalized']

In [54]:
d0.head()

delivery_area_id                date  orders_cnt  hour  weekday  \
0                 0 2021-04-01 10:00:00           9    10        3   
1                 0 2021-04-01 11:00:00           1    11        3   
2                 0 2021-04-01 13:00:00           1    13        3   
3                 0 2021-04-01 14:00:00           1    14        3   
4                 0 2021-04-01 15:00:00           2    15        3   

   orders_cnt_normalized  orders_cnt_finally_normalized  
0                    2.0                            4.5  
1                    2.0                            0.5  
2                    2.0                            0.5  
3                    2.0                            0.5  
4                    2.0                            1.0